### ISSUE TITLE
My character keeps on teleporting

### ISSUE THREAD

**Issue by Sweg1b01** [Leather128/LeathersFNFModPorts#2]
my offsets for my character that i used work perfectly in other engines but when i put em into leather they teleport around im using the shaggy json, xml and sprite sheet and these are the offsets used

idle 0 0
singUP -16 27
singRIGHT -1 38
singLEFT 165 -114
singDOWN -10 -160

please find a way to make my playable shaggy not teleport as i click the arrows.

**Comment by Sweg1b01** [comment]
heres a updated one its better

idle 0 0
singDOWN 93 -150
singRIGHT 86 -150
singUP -58 20
singLEFT -46 -20

please i need this fixed :/

**Comment by Leather128** [comment]
why did you put this issue on the mod port repo tho lol
